### ISSUE TITLE
Wrong stance bar positioning after stance change in combat

### ISSUE THREAD

**Issue by igritsay** [domino54/CompactActionBar#3]
![stance_bar_issue](https://user-images.githubusercontent.com/9950816/102466473-bf416b00-4057-11eb-9014-9413a2b4da24.gif)

**Comment by igritsay** [comment]
Bloodrage just was an easiest way to enter in combat mode, but same behaviour will occur if you change stance being in combat without bloodrage.

**Comment by Ansi** [comment]
Happens with rogue stance as well

**Comment by domino54** [comment]
I have noticed it happening while playing a paladin too. Will take a look into that.

Some other elements also tend to move slightly, I'll check the possibilities of disabling original position update functions in blizz UI, which should hopefully fix that.

**Comment by domino54** [comment]
It should be now fixed in version 1.2.3 going up soon. If that still persists, please open a new issue. Sorry for the short delay. 😃
